trigger:
- deploy/production
- deploy/staging
- deploy/development

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: wpengine-pipeline.template.yml
  parameters:
    gitEmail: 'maitryee.zaveri@wpengine.com'
    gitUser: 'Maitryee Zaveri'
    productionGit: 'git@git.wpengine.com:production/maitryee.git'
    productionBranch: 'deploy/production'
    stagingGit: 'git@git.wpengine.com:production/multimzstg.git'
    stagingBranch: 'deploy/staging'
    developmentGit: 'git@git.wpengine.com:production/maitryeedev.git'
    developmentBranch: 'deploy/development'
    
    #testing
