trigger:
- deploy/production

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: wpengine-pipeline.template.yml
  parameters:
    gitEmail: 'maitryee.zaveri@wpengine.com'
    gitUser: 'Maitryee Zaveri'
    productionGit: 'git@git.wpengine.com:production/maitryee.git'
    productionBranch: 'deploy/production'
